# 2.1 NumPy: основы и векторизация

Цели:
- Понять создание массивов `ndarray`, типы, форму.
- Отработать срезы, булевы маски, broadcasting.
- Сравнить векторизованный и циклический код по времени.


In [1]:
import numpy as np

## 1. Массивы: форма и типы

In [7]:
# Create arrays with specific dtypes and shapes, explore .shape/.ndim/.dtype
a = np.arange(12).reshape(3, 4)
a, a.shape, a.ndim, a.dtype

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4),
 2,
 dtype('int64'))

In [2]:
zeros_array = np.zeros(10)
ones_array = np.ones(10)
constant_array = np.full(10, 3)
linspace_array = np.linspace(0, 1, 11)

zeros_array, ones_array, constant_array, linspace_array

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

In [13]:
arr1 = np.ones(4)
arr2 = np.full(4, 3)
arr1 + arr2, arr1 / arr2, arr2

(array([4., 4., 4., 4.]),
 array([0.33333333, 0.33333333, 0.33333333, 0.33333333]),
 array([3, 3, 3, 3]))

In [3]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
arr[0], arr[:, 0]

(array([2, 3, 4]), array([2, 4]))

In [4]:
np.random.seed(2)  # Set the seed
random_array = np.random.rand(5, 2)  # Generates random numbers between 0 and 1
normal_distribution = np.random.randn(5, 2)
random_integers = np.random.randint(low=0, high=100, size=(5, 2))
random_array, random_integers

(array([[0.4359949 , 0.02592623],
        [0.54966248, 0.43532239],
        [0.4203678 , 0.33033482],
        [0.20464863, 0.61927097],
        [0.29965467, 0.26682728]]),
 array([[83, 31],
        [66, 80],
        [52, 76],
        [50,  4],
        [90, 63]]))

## 2. Срезы и булевы маски

In [8]:
# Use boolean indexing to select rows/cols meeting a condition
mask = a % 2 == 0
a[mask][:5]

array([0, 2, 4, 6, 8])

## 3. Broadcasting (распространение операций)

In [9]:
# Add a row vector to all rows via broadcasting
row = np.array([1, 0, -1, 2])
a + row

array([[ 1,  1,  1,  5],
       [ 5,  5,  5,  9],
       [ 9,  9,  9, 13]])

In [10]:
arr = np.array([1, 2, 3, 4])
arr > 2  # Produces [False, False, True, True]

array([False, False,  True,  True])

## 4. Тайминг: циклы vs векторизация

In [17]:
import time
# Compare runtime for element-wise operation: loop vs vectorized
n = 300_000
x = np.random.rand(n)
# Loop
t0 = time.time()
y_loop = [xi * 2.0 + 1.0 for xi in x]
t1 = time.time()
# Vectorized
t2 = time.time()
y_vec = x * 2.0 + 1.0
t3 = time.time()
t_loop, t_vec = t1 - t0, t3 - t2
t_loop, t_vec

(0.25087833404541016, 0.004433631896972656)