# 2.2 Линейная алгебра в NumPy

Цели:
- Отработать матричные операции (`@`, `dot`), транспонирование.
- Решение СЛАУ и обсуждение обусловленности.
- Нормы, введение в собственные значения/SVD.


In [2]:
import numpy as np
from numpy.linalg import norm, solve, eig, svd
np.__version__

'2.4.1'

## 1. Умножение и транспонирование

In [3]:
# Demonstrate A @ B vs np.dot(A,B), and (A.T) properties
A = np.arange(9).reshape(3,3)
B = np.eye(3) * 2
A @ B, np.dot(A, B), A.T

(array([[ 0.,  2.,  4.],
        [ 6.,  8., 10.],
        [12., 14., 16.]]),
 array([[ 0.,  2.,  4.],
        [ 6.,  8., 10.],
        [12., 14., 16.]]),
 array([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]]))

In [5]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

In [6]:
# addition 
u + v

array([ 5, 11, 13, 12])

In [7]:
# subtraction 
u - v

array([-1,  3, -3,  0])

In [8]:
# scalar multiplication 
2 * v

array([ 6,  8, 16, 12])

## 2. Решение СЛАУ Ax=b

In [3]:
# Solve and check residual
rng = np.random.default_rng(42)
A = rng.normal(size=(5,5))
b = rng.normal(size=5)
x = solve(A, b)
res = norm(A @ x - b)
res

np.float64(2.6622212897024595e-16)

## 3. Нормы и обусловленность

In [4]:
# Compute norms and condition number (via SVD)
U, s, Vt = svd(A)
cond_num = s.max() / s.min()
cond_num

np.float64(6.693673474532081)

## 4. Собственные значения и векторы

In [5]:
# Eigen-decomposition for a symmetric matrix
S = A + A.T
w, v = eig(S)
w[:5]

array([-5.01991446,  3.10557781,  0.40265518,  1.46802769,  1.9410751 ])