# 2.1 NumPy: основы и векторизация

Цели:
- Понять создание массивов `ndarray`, типы, форму.
- Отработать срезы, булевы маски, broadcasting.
- Сравнить векторизованный и циклический код по времени.


In [2]:
import numpy as np

## 1. Массивы: форма и типы

In [3]:
# Create arrays with specific dtypes and shapes, explore .shape/.ndim/.dtype
a = np.arange(12).reshape(3, 4)
a, a.shape, a.ndim, a.dtype

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4),
 2,
 dtype('int64'))

In [5]:
zeros_array = np.zeros(10)
ones_array = np.ones(10)
constant_array = np.full(10, 3)

zeros_array, ones_array, constant_array

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3]))

In [13]:
arr1 = np.ones(4)
arr2 = np.full(4, 3)
arr1 + arr2, arr1 / arr2, arr2

(array([4., 4., 4., 4.]),
 array([0.33333333, 0.33333333, 0.33333333, 0.33333333]),
 array([3, 3, 3, 3]))

In [15]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
arr[0], arr[:, 0]

(array([2, 3, 4]), array([2, 4]))

## 2. Срезы и булевы маски

In [12]:
# Use boolean indexing to select rows/cols meeting a condition
mask = a % 2 == 0
a[mask][:5]

array([0, 2, 4, 6, 8])

## 3. Broadcasting (распространение операций)

In [11]:
# Add a row vector to all rows via broadcasting
row = np.array([1, 0, -1, 2])
a + row

array([[ 1,  1,  1,  5],
       [ 5,  5,  5,  9],
       [ 9,  9,  9, 13]])

## 4. Тайминг: циклы vs векторизация

In [17]:
import time
# Compare runtime for element-wise operation: loop vs vectorized
n = 300_000
x = np.random.rand(n)
# Loop
t0 = time.time()
y_loop = [xi * 2.0 + 1.0 for xi in x]
t1 = time.time()
# Vectorized
t2 = time.time()
y_vec = x * 2.0 + 1.0
t3 = time.time()
t_loop, t_vec = t1 - t0, t3 - t2
t_loop, t_vec

(0.25087833404541016, 0.004433631896972656)